@baseUrl = http://localhost:3001


# Reminder

###
# find all reminders
GET {{baseUrl}}/reminder
?limit=10
&offset=10
&searchText=""
###


###
# find one reminder
GET {{baseUrl}}/reminder/95af33d3-cb69-4c32-b9cc-bc11f2a8121f
###

###
# create one reminder
POST {{baseUrl}}/reminder
Content-Type: application/json

{
  "description":"Esse é o recado 3",
  "from":"Joana",
  "to":"Atlas"
}
###


###
# update one reminder
PATCH {{baseUrl}}/reminder/1
Content-Type: application/json

{
  "description":"Esse é o recado"
}
###


###
# delete one reminder
DELETE  {{baseUrl}}/reminder/1
###
